### ISSUE TITLE
Add Enter and close function to GameState

### ISSUE THREAD

**Issue by klinginE** [klinginE/Shogun-GameEngine#19]
When a state becomes the top of the game stack it's enter function gets called when the game closes all state close functions get called.

**Comment by richard-barella** [comment]
The virtual functions added are "enter", "leave", "pause", and "resume" for when the state "enters" the stack, "leaves" the stack, gets "paused" and another state is pushed on top of it on the stack, and "resumes" when the state on top of it is popped off the stack.
